apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gym-frontend
  labels:
    app: ai-gym-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-gym-frontend
  template:
    metadata:
      labels:
        app: ai-gym-frontend
    spec:
      containers:
      - name: ai-gym-frontend
        image: your-registry/ai-gym-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-gym-frontend-service
  labels:
    app: ai-gym-frontend
spec:
  selector:
    app: ai-gym-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-gym-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-gym-frontend-service
            port:
              number: 80
