# AI GYM Frontend - Cloudflare Pages Configuration
# Para desplegar aplicación React con Vite en Cloudflare Pages

name = "aigym-minimax-ezez"
compatibility_date = "2024-09-01"

# Configuración específica para Cloudflare Pages
pages_build_output_dir = "ai-gym-frontend/ai-gym-frontend/dist"

